name: college_lms
description: "**Learning Management System (LMS)** is a digital platform designed to manage and simplify academic activities. It allows students and teachers to access courses, attendance, assignments, quizzes, results, and important notices in one place."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
